use model::Token;

/// Maps an identifier string to a keyword token, or returns None if not a keyword
pub fn keyword_or_identifier(value: &str) -> Token {
    match value {
        "int" => Token::Int,
        "void" => Token::Void,
        "return" => Token::Return,
        "if" => Token::If,
        "else" => Token::Else,
        "while" => Token::While,
        "for" => Token::For,
        "do" => Token::Do,
        "break" => Token::Break,
        "continue" => Token::Continue,
        "goto" => Token::Goto,
        "switch" => Token::Switch,
        "case" => Token::Case,
        "default" => Token::Default,
        "static" => Token::Static,
        "extern" => Token::Extern,
        "inline" => Token::Inline,
        "const" => Token::Const,
        "volatile" => Token::Volatile,
        "__volatile" => Token::Volatile,
        "__volatile__" => Token::Volatile,
        "typedef" => Token::Typedef,
        "struct" => Token::Struct,
        "char" => Token::Char,
        "enum" => Token::Enum,
        "float" => Token::Float,
        "double" => Token::Double,
        "unsigned" => Token::Unsigned,
        "signed" => Token::Signed,
        "__signed" => Token::Signed,
        "__signed__" => Token::Signed,
        "long" => Token::Long,
        "short" => Token::Short,
        "union" => Token::Union,
        "asm" => Token::Asm,
        "__asm" => Token::Asm,
        "__asm__" => Token::Asm,
        "__attribute__" => Token::Attribute,
        "__extension__" => Token::Extension,
        "__inline" => Token::Inline,
        "__inline__" => Token::Inline,
        "restrict" => Token::Restrict,
        "__restrict" => Token::Restrict,
        "__restrict__" => Token::Restrict,
        "__cdecl" => Token::Extension,
        "__stdcall" => Token::Extension,
        "__fastcall" => Token::Extension,
        "__thiscall" => Token::Extension,
        "__cdecl__" => Token::Extension,
        "__stdcall__" => Token::Extension,
        "__fastcall__" => Token::Extension,
        "__thiscall__" => Token::Extension,
        "__nonnull" => Token::Extension,
        "__leaf__" => Token::Extension,
        "__nothrow__" => Token::Extension,
        "__pure__" => Token::Extension,
        "__const__" => Token::Const,
        "sizeof" => Token::SizeOf,
        "typeof" => Token::Typeof,
        "__typeof" => Token::Typeof,
        "__typeof__" => Token::Typeof,
        "_Static_assert" => Token::StaticAssert,
        "static_assert" => Token::StaticAssert,
        _ => Token::Identifier { value: value.to_string() },
    }
}
