use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use model::{BinaryOp, UnaryOp, Type, GlobalVar as AstGlobalVar};

/// Variable identifier in IR
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VarId(pub usize);

/// Basic block identifier in IR
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct BlockId(pub usize);

/// Operand in IR instructions - can be a constant, variable, or global
#[derive(Debug, Clone, PartialEq)]
pub enum Operand {
    Constant(i64),
    FloatConstant(f64),
    Var(VarId),
    Global(String),
}

impl Eq for Operand {}

impl Hash for Operand {
    fn hash<H: Hasher>(&self, state: &mut H) {
        std::mem::discriminant(self).hash(state);
        match self {
            Operand::Constant(v) => v.hash(state),
            Operand::FloatConstant(v) => v.to_bits().hash(state),
            Operand::Var(v) => v.hash(state),
            Operand::Global(s) => s.hash(state),
        }
    }
}

/// IR Instructions in SSA form
#[derive(Debug, Clone)]
pub enum Instruction {
    Binary {
        dest: VarId,
        op: BinaryOp,
        left: Operand,
        right: Operand,
    },
    FloatBinary {
        dest: VarId,
        op: BinaryOp,
        left: Operand,
        right: Operand,
    },
    Unary {
        dest: VarId,
        op: UnaryOp,
        src: Operand,
    },
    FloatUnary {
        dest: VarId,
        op: UnaryOp,
        src: Operand,
    },
    Phi {
        dest: VarId,
        // (BlockId where the value comes from, VarId)
        preds: Vec<(BlockId, VarId)>,
    },
    Copy {
        dest: VarId,
        src: Operand,
    },
    Cast {
        dest: VarId,
        src: Operand,
        r#type: Type,
    },
    Alloca {
        dest: VarId,
        r#type: Type,
    },
    Load {
        dest: VarId,
        addr: Operand,
        value_type: Type, // Type of the value being loaded
        volatile: bool,
    },
    Store {
        addr: Operand,
        src: Operand,
        value_type: Type, // Type of the value being stored
        volatile: bool,
    },
    GetElementPtr {
        dest: VarId,
        base: Operand,
        index: Operand,
        element_type: Type,
    },
    Call {
        dest: Option<VarId>,
        name: String,
        args: Vec<Operand>,
    },
    IndirectCall {
        dest: Option<VarId>,
        func_ptr: Operand,
        args: Vec<Operand>,
    },
    // Variadic intrinsics
    VaStart {
        list: Operand,
        arg_index: usize, // Index of the last named argument
    },
    VaEnd {
        list: Operand,
    },
    VaCopy {
        dest: Operand,
        src: Operand,
    },
    VaArg {
        dest: VarId,
        list: Operand,
        r#type: Type,
    },
    InlineAsm {
        template: String,
        outputs: Vec<VarId>,     // Output variables
        inputs: Vec<Operand>,    // Input operands
        output_constraints: Vec<String>, // "=r", "=m", "+r", etc.
        input_constraints: Vec<String>,  // "r", "m", "i", etc.
        clobbers: Vec<String>,   // Clobbered registers
        is_volatile: bool,
    },
    /// SIMD vector instruction (generated by auto-vectorizer)
    Simd {
        op: SimdOp,
        dest: Option<VarId>,     // Some for Load/Add/Sub/Mul/HAdd, None for Store
        operands: Vec<Operand>,  // addresses, source vector vars
        elem_type: Type,         // element type (Int, Float)
        width: usize,            // vector width: 4 (SSE) or 8 (AVX2)
    },
}

impl Instruction {
    /// Get the destination VarId defined by this instruction, if any.
    pub fn dest(&self) -> Option<VarId> {
        match self {
            Instruction::Binary { dest, .. }
            | Instruction::FloatBinary { dest, .. }
            | Instruction::Unary { dest, .. }
            | Instruction::FloatUnary { dest, .. }
            | Instruction::Phi { dest, .. }
            | Instruction::Copy { dest, .. }
            | Instruction::Cast { dest, .. }
            | Instruction::Alloca { dest, .. }
            | Instruction::Load { dest, .. }
            | Instruction::GetElementPtr { dest, .. }
            | Instruction::VaArg { dest, .. } => Some(*dest),
            Instruction::Call { dest, .. }
            | Instruction::IndirectCall { dest, .. } => *dest,
            Instruction::Simd { dest, .. } => *dest,
            Instruction::InlineAsm { outputs, .. } => outputs.first().copied(),
            Instruction::Store { .. }
            | Instruction::VaStart { .. }
            | Instruction::VaEnd { .. }
            | Instruction::VaCopy { .. } => None,
        }
    }

    /// Get all destination VarIds defined by this instruction.
    /// For most instructions this is 0 or 1; InlineAsm may have multiple outputs.
    pub fn dests(&self) -> Vec<VarId> {
        match self {
            Instruction::InlineAsm { outputs, .. } => outputs.clone(),
            _ => self.dest().into_iter().collect(),
        }
    }

    /// Visit all VarIds used (read) by this instruction.
    pub fn for_each_use<F: FnMut(VarId)>(&self, mut f: F) {
        let visit_op = |op: &Operand, f: &mut F| {
            if let Operand::Var(v) = op { f(*v); }
        };
        match self {
            Instruction::Binary { left, right, .. }
            | Instruction::FloatBinary { left, right, .. } => {
                visit_op(left, &mut f);
                visit_op(right, &mut f);
            }
            Instruction::Unary { src, .. }
            | Instruction::FloatUnary { src, .. }
            | Instruction::Copy { src, .. }
            | Instruction::Cast { src, .. } => {
                visit_op(src, &mut f);
            }
            Instruction::Load { addr, .. } => {
                visit_op(addr, &mut f);
            }
            Instruction::Store { addr, src, .. } => {
                visit_op(addr, &mut f);
                visit_op(src, &mut f);
            }
            Instruction::GetElementPtr { base, index, .. } => {
                visit_op(base, &mut f);
                visit_op(index, &mut f);
            }
            Instruction::Call { args, .. } => {
                for arg in args { visit_op(arg, &mut f); }
            }
            Instruction::IndirectCall { func_ptr, args, .. } => {
                visit_op(func_ptr, &mut f);
                for arg in args { visit_op(arg, &mut f); }
            }
            Instruction::Phi { preds, .. } => {
                for (_, v) in preds { f(*v); }
            }
            Instruction::VaStart { list, .. } => { visit_op(list, &mut f); }
            Instruction::VaEnd { list } => { visit_op(list, &mut f); }
            Instruction::VaCopy { dest, src } => {
                visit_op(dest, &mut f);
                visit_op(src, &mut f);
            }
            Instruction::VaArg { list, .. } => { visit_op(list, &mut f); }
            Instruction::InlineAsm { inputs, .. } => {
                for input in inputs { visit_op(input, &mut f); }
            }
            Instruction::Alloca { .. } => {}
            Instruction::Simd { operands, .. } => {
                for op in operands { visit_op(op, &mut f); }
            }
        }
    }

    /// Visit all operand references mutably, allowing in-place replacement.
    pub fn for_each_operand_mut<F: FnMut(&mut Operand)>(&mut self, mut f: F) {
        match self {
            Instruction::Binary { left, right, .. }
            | Instruction::FloatBinary { left, right, .. } => {
                f(left);
                f(right);
            }
            Instruction::Unary { src, .. }
            | Instruction::FloatUnary { src, .. }
            | Instruction::Copy { src, .. }
            | Instruction::Cast { src, .. } => {
                f(src);
            }
            Instruction::Load { addr, .. } => {
                f(addr);
            }
            Instruction::Store { addr, src, .. } => {
                f(addr);
                f(src);
            }
            Instruction::GetElementPtr { base, index, .. } => {
                f(base);
                f(index);
            }
            Instruction::Call { args, .. } => {
                for arg in args { f(arg); }
            }
            Instruction::IndirectCall { func_ptr, args, .. } => {
                f(func_ptr);
                for arg in args { f(arg); }
            }
            Instruction::Phi { preds, .. } => {
                // Phi operands are VarIds, not Operands — skip here.
                // Use for_each_phi_var_mut for phi sources.
                let _ = preds;
            }
            Instruction::VaStart { list, .. } => { f(list); }
            Instruction::VaEnd { list } => { f(list); }
            Instruction::VaCopy { dest, src } => {
                f(dest);
                f(src);
            }
            Instruction::VaArg { list, .. } => { f(list); }
            Instruction::InlineAsm { inputs, .. } => {
                for input in inputs { f(input); }
            }
            Instruction::Alloca { .. } => {}
            Instruction::Simd { operands, .. } => {
                for op in operands { f(op); }
            }
        }
    }

    /// Returns true if this instruction has side effects (stores, calls, etc.)
    /// and should not be removed even if its result is unused.
    pub fn has_side_effects(&self) -> bool {
        match self {
            Instruction::Load { volatile: true, .. } => true,
            _ => matches!(self,
                Instruction::Store { .. }
                | Instruction::Call { .. }
                | Instruction::IndirectCall { .. }
                | Instruction::InlineAsm { .. }
                | Instruction::Alloca { .. }
                | Instruction::VaStart { .. }
                | Instruction::VaEnd { .. }
                | Instruction::VaCopy { .. }
                | Instruction::VaArg { .. }
                | Instruction::Simd { .. }
            )
        }
    }
}

/// SIMD operation kind
#[derive(Debug, Clone, PartialEq)]
pub enum SimdOp {
    /// Vector load from contiguous memory
    Load,
    /// Vector store to contiguous memory
    Store,
    /// Element-wise addition
    Add,
    /// Element-wise subtraction
    Sub,
    /// Element-wise multiplication
    Mul,
    /// Element-wise bitwise AND (integer vectors)
    And,
    /// Element-wise bitwise OR (integer vectors)
    Or,
    /// Element-wise bitwise XOR (integer vectors)
    Xor,
    /// Horizontal add — reduces vector to scalar sum
    HorizontalAdd,
    /// Broadcast scalar to all vector lanes
    Splat,
    /// Per-lane mask: lane k active iff (iv + k) < bound. Operands: [iv, bound].
    LaneMask,
    /// Merge vectors: inactive lanes from `operands[0]`, active from `operands[1]`, mask `operands[2]`.
    Blend,
}

/// Control flow terminators for basic blocks
#[derive(Debug, Clone)]
pub enum Terminator {
    Br(BlockId),
    CondBr {
        cond: Operand,
        then_block: BlockId,
        else_block: BlockId,
    },
    Ret(Option<Operand>),
    Unreachable,
}

/// Basic block with instructions and terminator
#[derive(Debug, Clone)]
pub struct BasicBlock {
    pub id: BlockId,
    pub instructions: Vec<Instruction>,
    pub terminator: Terminator,
    /// True if this block is a target of a goto/label statement (should not be merged)
    pub is_label_target: bool,
}

/// Function in IR form
#[derive(Debug, Clone)]
pub struct Function {
    pub name: String,
    pub return_type: Type,
    pub params: Vec<(Type, VarId)>,
    pub blocks: Vec<BasicBlock>,
    pub entry_block: BlockId,
    /// Type annotations for IR variables (used to distinguish float/int in codegen)
    pub var_types: HashMap<VarId, Type>,
    /// Function attributes (weak, section, noreturn, etc.)
    pub attributes: Vec<model::Attribute>,
    /// Whether this function has internal (static) linkage
    pub is_static: bool,
}

impl Function {
    /// Compute a predecessor map for all blocks in this function.
    ///
    /// Returns a mapping from each `BlockId` to the list of `BlockId`s whose
    /// terminators branch to it.  This is O(n) in the number of blocks.
    pub fn compute_predecessors(&self) -> HashMap<BlockId, Vec<BlockId>> {
        let mut preds: HashMap<BlockId, Vec<BlockId>> = HashMap::new();
        for block in &self.blocks {
            preds.entry(block.id).or_default();
        }
        for block in &self.blocks {
            match &block.terminator {
                Terminator::Br(target) => {
                    preds.entry(*target).or_default().push(block.id);
                }
                Terminator::CondBr { then_block, else_block, .. } => {
                    preds.entry(*then_block).or_default().push(block.id);
                    preds.entry(*else_block).or_default().push(block.id);
                }
                _ => {}
            }
        }
        preds
    }

    /// Compute a successor map for all blocks in this function.
    pub fn compute_successors(&self) -> HashMap<BlockId, Vec<BlockId>> {
        let mut succs: HashMap<BlockId, Vec<BlockId>> = HashMap::new();
        for block in &self.blocks {
            let mut s = Vec::new();
            match &block.terminator {
                Terminator::Br(target) => s.push(*target),
                Terminator::CondBr { then_block, else_block, .. } => {
                    s.push(*then_block);
                    s.push(*else_block);
                }
                _ => {}
            }
            succs.insert(block.id, s);
        }
        succs
    }
}

/// Complete IR program
#[derive(Debug, Clone)]
pub struct IRProgram {
    pub functions: Vec<Function>,
    pub global_strings: Vec<(String, String)>, // (label, content)
    pub globals: Vec<AstGlobalVar>,
    pub structs: Vec<model::StructDef>,
    pub unions: Vec<model::UnionDef>,
}
